parameters:
    cms_admin.form.type.richeditor.class: Cms\Bundle\AdminBundle\Form\Extension\Type\RichEditorType
    cms_admin.form.type.image.class: Cms\Bundle\AdminBundle\Form\Extension\Type\ImageType

services:
            
    form.type.richeditor:
        class: %cms_admin.form.type.richeditor.class%
        tags:
            - { name: form.type, alias: richeditor }
            
    form.type.image:
        class: %cms_admin.form.type.image.class%
        tags:
            - { name: form.type, alias: image }
