<?php

namespace Cms\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseAdminEntityRepository extends EntityRepository {
	
	public static $default_alias = 't';
	
	public function deleteGroup($ids) {
        $qb = $this->createQueryBuilder(self::$default_alias);

        $qb->delete()
                ->where($qb->expr()->in(self::$default_alias.'.id', $ids))
                ->getQuery()
                ->execute();

        $this->_em->flush();
    }
}