stfalcon_tinymce:
  include_jquery: false
  tinymce_jquery: true
  selector: ".tinymce"
  # Get current language from the parameters.ini
  language: %locale%
  theme:
    # Simple theme: same as default theme
    simple: ~
    # Advanced theme with almost all enabled plugins
    advanced:
      plugins:
        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "insertdatetime media nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
      toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
      image_advtab: true
