cms_admin_admin_user_index:
    path: /
    defaults: { _controller: "CmsAdminBundle:AdminUser:index" }

cms_admin_admin_user_new:
    path: /new
    defaults: { _controller: "CmsAdminBundle:AdminUser:new" }
    requirements:
    methods: [GET]
cms_admin_admin_user_create:
    path: /create
    defaults: { _controller: "CmsAdminBundle:AdminUser:create" }
    requirements:
    methods: [POST]

cms_admin_admin_user_delete:
    path: /{id}/delete
    defaults: { _controller: "CmsAdminBundle:AdminUser:delete" }
    requirements:
      id: \d+
    methods: [DELETE]

cms_admin_admin_user_edit:
    path: /{id}/edit
    defaults: { _controller: "CmsAdminBundle:AdminUser:edit" }
    requirements:
      id: \d+
    methods: [GET]
cms_admin_admin_user_update:
    path: /{id}/update
    defaults: { _controller: "CmsAdminBundle:AdminUser:update" }
    requirements:
      id: \d+
    methods: [PUT]

cms_admin_admin_user_group_process:
    path: /group_process
    defaults: { _controller: "CmsAdminBundle:AdminUser:groupProcess" }
    requirements:
    methods: [POST]
